// <auto-generated />
using Infra.Data.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Data.Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entity.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("comandas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 5,
                            UsuarioId = 4
                        });
                });

            modelBuilder.Entity("Domain.Entity.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComandaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.ToTable("produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComandaId = 1,
                            Nome = "X-Salada",
                            Preco = 30.00m
                        },
                        new
                        {
                            Id = 2,
                            ComandaId = 1,
                            Nome = "X-Bacon",
                            Preco = 35.00m
                        },
                        new
                        {
                            Id = 3,
                            ComandaId = 2,
                            Nome = "Pizza Margherita",
                            Preco = 45.00m
                        },
                        new
                        {
                            Id = 4,
                            ComandaId = 3,
                            Nome = "X-Tudo",
                            Preco = 42.50m
                        },
                        new
                        {
                            Id = 5,
                            ComandaId = 3,
                            Nome = "Batata Frita Grande",
                            Preco = 25.00m
                        },
                        new
                        {
                            Id = 6,
                            ComandaId = 3,
                            Nome = "Refrigerante 2L",
                            Preco = 22.00m
                        },
                        new
                        {
                            Id = 7,
                            ComandaId = 4,
                            Nome = "Hot Dog Especial",
                            Preco = 18.50m
                        },
                        new
                        {
                            Id = 8,
                            ComandaId = 4,
                            Nome = "Suco Natural",
                            Preco = 14.00m
                        },
                        new
                        {
                            Id = 9,
                            ComandaId = 5,
                            Nome = "Pizza Portuguesa",
                            Preco = 48.00m
                        },
                        new
                        {
                            Id = 10,
                            ComandaId = 5,
                            Nome = "Guaraná Lata",
                            Preco = 8.00m
                        },
                        new
                        {
                            Id = 11,
                            ComandaId = 5,
                            Nome = "Sobremesa Pudim",
                            Preco = 22.00m
                        });
                });

            modelBuilder.Entity("Domain.Entity.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "joao.silva@email.com",
                            Nome = "João Silva",
                            Senha = "admin123",
                            Telefone = "47988887777"
                        },
                        new
                        {
                            Id = 2,
                            Email = "maria.santos@email.com",
                            Nome = "Maria Santos",
                            Senha = "admin123",
                            Telefone = "47999998888"
                        },
                        new
                        {
                            Id = 3,
                            Email = "pedro.oliveira@email.com",
                            Nome = "Pedro Oliveira",
                            Senha = "admin123",
                            Telefone = "47977776666"
                        },
                        new
                        {
                            Id = 4,
                            Email = "ana.costa@email.com",
                            Nome = "Ana Costa",
                            Senha = "admin123",
                            Telefone = "47966665555"
                        },
                        new
                        {
                            Id = 5,
                            Email = "carlos.mendes@email.com",
                            Nome = "Carlos Mendes",
                            Senha = "admin123",
                            Telefone = "47955554444"
                        });
                });

            modelBuilder.Entity("Domain.Entity.Comanda", b =>
                {
                    b.HasOne("Domain.Entity.Usuario", "Usuario")
                        .WithMany("Comandas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entity.Produto", b =>
                {
                    b.HasOne("Domain.Entity.Comanda", "Comanda")
                        .WithMany("Produtos")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("Domain.Entity.Comanda", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Domain.Entity.Usuario", b =>
                {
                    b.Navigation("Comandas");
                });
#pragma warning restore 612, 618
        }
    }
}
